name: TutorialPlugin
main: de.verkleckst.Tutorial.Hauptklasse
author: verkleckst
version: 1.0
commands:
   heal:
     description: Heilen
     aliases: h
   tp:
     description: Teleportiern
     aliases: minecraft:tp